### PR TITLE
Update ToggleDarkMode.svelte

### PR DESCRIPTION
**Pull request by npiyush97**
Light mode / Dark mode doesn't get saved #6

fix / cleaning required 
sorry but forget to remove console.log

### CODE REVIEW

**Comment by npiyush97** [comment]
sorry for late reply but can i ask what test this code is failing upon it is working fine on my browser.
Thank you

**Comment by npiyush97** [comment]
and i also fix the padding issue because there is a change in padding while toggle

**Comment by npiyush97** [comment]
https://user-images.githubusercontent.com/43876655/154859433-311b3307-510b-4685-9f23-ce051d625a4b.mp4

**Comment by TetrisIQ** [comment]
If I checkout your branch and run `yarn run build` it's failing due to compiling issues. Also, if you look at your changed files, you see that your function `setMode` never gets called. 

I fixed this.

**Comment by npiyush97** [comment]
i dont know i tried and test on chrome firefox and opera work as suppose to.How did you fixed it ?

**Comment by TetrisIQ** [comment]
Take a look at [my Commit](https://github.com/TetrisIQ/poll-dapp/pull/23/commits/4d6aee91819ccf11f3f995857041a4de3f1fd4aa) I call `setMode()` and remove some unnecessary brackets.

**Comment by npiyush97** [comment]
sorry for keeping comment bracket were inuse that was a anonymous function it will run on every re-render.
last comment

**Pull request merged**
